---
"production-infrastructure":
    version: 10
    deps:
        - "erlang"
        - "rabbitmq"
        - "elasticsearch"
        -
          "formula" : "ensembl/web/nginx-full"
          "options" : ["with-sub"]
